CREATE TABLE T1 
(
SUBJECT VARCHAR(10) PRIMARY KEY,
SCORE INT
 )
 
 SELECT * FROM T1
 
 
 INSERT INTO T1 (SUBJECT,SCORE)
 VALUES
 ('PHY', 70),
 ('CHEM', 80),
 ('MATHS', 90)
 
 SELECT * FROM T1


SELECT
    MAX(CASE WHEN SUBJECT = 'PHY' THEN score END) AS PHY,
    MAX(CASE WHEN SUBJECT = 'CHEM' THEN score END) AS CHEM,
    MAX(CASE WHEN SUBJECT = 'MATHS' THEN score END) AS MATHS
FROM
    T1;
